"use client"

import { CheckCircle2, Circle } from "lucide-react"
import { useState } from "react"
import { cn } from "@/lib/utils"

const initialTasks = [
  { id: 1, day: "Monday", task: "Finish React Tutorial", done: true },
  { id: 2, day: "Tuesday", task: "Write API Route", done: true },
  { id: 3, day: "Wednesday", task: "Wire frontend to backend", done: false },
  { id: 4, day: "Thursday", task: "Add authentication", done: false },
  { id: 5, day: "Friday", task: "Deploy to Vercel", done: false },
]

export default function WeeklyPlanner() {
  const [tasks, setTasks] = useState(initialTasks)

  const toggleTask = (id: number) => {
    setTasks(tasks.map(t => t.id === id ? { ...t, done: !t.done } : t))
  }

  return (
    <div className="bg-slate-900 rounded-xl border border-slate-800 p-6 flex flex-col h-full shadow-lg">
      <div className="flex items-center justify-between mb-6">
        <h3 className="text-lg font-bold text-white">Weekly Plan</h3>
        <span className="text-xs font-medium bg-slate-800 text-slate-300 px-2 py-1 rounded">Generated by AI</span>
      </div>
      
      <div className="flex-1 space-y-3">
        {tasks.map((task) => (
          <div 
            key={task.id}
            onClick={() => toggleTask(task.id)}
            className="flex items-center gap-4 p-3 rounded-lg hover:bg-slate-800/50 transition cursor-pointer group"
          >
            {task.done ? (
              <CheckCircle2 className="h-5 w-5 text-emerald-500" />
            ) : (
              <Circle className="h-5 w-5 text-slate-500 group-hover:text-emerald-500/50 transition" />
            )}
            
            <div className="flex flex-col">
              <span className={cn(
                "font-medium transition",
                task.done ? "text-slate-400 line-through" : "text-slate-200 group-hover:text-white"
              )}>
                {task.task}
              </span>
              <span className="text-xs text-slate-500">{task.day}</span>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}
